services:
  composer:
    image: rareloop/php-composer:php-8.2-cli-composer-2
    container_name: alpes-composer
    working_dir: /var/www/html
    user: www-data
    volumes:
      - ./:/var/www/html
    command: sh -lc "composer install --no-interaction --prefer-dist --optimize-autoloader"

  artisan-setup:
    image: rareloop/php-composer:php-8.2-cli-composer-2
    container_name: alpes-artisan-setup
    working_dir: /var/www/html
    user: www-data
    volumes:
      - ./:/var/www/html
    depends_on:
      composer:
        condition: service_completed_successfully
    command: >
      sh -lc "
      mkdir -p database &&
      touch database/database.sqlite &&
      chown -R www-data:www-data storage bootstrap/cache database &&
      php artisan key:generate --force &&
      php artisan migrate --seed --force
      "

  # 3) App PHP-FPM (fica rodando)
  alpes:
    image: jkaninda/laravel-php-fpm
    container_name: alpes
    restart: unless-stopped
    user: www-data
    volumes:
      - ./:/var/www/html
    depends_on:
      artisan-setup:
        condition: service_completed_successfully
    networks:
      - default

  # 4) Worker do scheduler
  alpes-worker:
    image: rareloop/php-composer:php-8.2-cli-composer-2
    container_name: alpes-worker
    restart: unless-stopped
    depends_on:
      alpes:
        condition: service_started
    user: www-data
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    command: php artisan schedule:work
    networks:
      - default

  # 5) Nginx
  nginx-server:
    image: jkaninda/nginx-fpm:alpine
    container_name: nginx-server
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
    environment:
      - DOCUMENT_ROOT=/var/www/html/public
      - CLIENT_MAX_BODY_SIZE=20M
      - PHP_FPM_HOST=alpes:9000
    depends_on:
      alpes:
        condition: service_started
    networks:
      - default

networks:
  default:
    driver: bridge
